version: "3.8"
services:
  app:
    build: ./app/
    depends_on:
      - postgis

  postgis:
    image: pgrouting/pgrouting:12-3.0-2.6.3
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=123456
      - HEALTH_TIMEOUT=60
    #options:
    #  - health-timeout 60s
volumes:
  db-data: